'use client';

import { useEffect, useState } from 'react';
import { accessOrder, type OrderResponse } from '@/lib/api';

const steps = ['new', 'confirmed', 'preparing', 'ready', 'completed'];
const labels: Record<string, string> = { awaiting_payment: 'Payment pending', new: 'Order submitted', confirmed: 'Order accepted', preparing: 'Preparing', ready: 'Ready / out for delivery', completed: 'Completed', cancelled: 'Cancelled' };
function money(value: number) { return `₦${value.toLocaleString('en-NG')}`; }
export default function OrderStatusView({ orderId, token }: { orderId: string; token: string }) {
  const [order, setOrder] = useState<OrderResponse | null>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  useEffect(() => { let active = true; if (!token) { setError('This order link is missing its secure access token.'); setLoading(false); return; } void accessOrder(orderId, token).then((value) => { if (active) setOrder(value); }).catch((err) => { if (active) setError(err instanceof Error ? err.message : 'We could not load this order.'); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [orderId, token]);
  if (loading) return <main className="tv-order-page"><p>Loading your order…</p></main>;
  if (error || !order) return <main className="tv-order-page"><p className="tv-checkout__error" role="alert">{error}</p><a className="tv-order-page__link" href="/menu">Return to menu</a></main>;
  const activeIndex = steps.indexOf(order.status);
  return <main className="tv-order-page"><header><p className="tv-eyebrow">Order #{order._id}</p><h1>Your order is {labels[order.status] || order.status}.</h1><p>Placed {new Intl.DateTimeFormat('en-NG', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'Africa/Lagos' }).format(new Date(order.createdAt))}</p></header><section className="tv-order-page__card"><div className="tv-order-page__status"><strong>{labels[order.status] || order.status}</strong><span>Payment: {order.paymentStatus === 'paid' ? 'Verified' : order.paymentStatus === 'receipt_submitted' ? 'Receipt submitted · verification pending' : order.paymentStatus}</span></div><ol className="tv-order-page__timeline">{steps.map((step, index) => <li key={step} data-current={step === order.status} data-complete={activeIndex >= index}><span>{activeIndex >= index ? '✓' : index + 1}</span>{labels[step]}</li>)}</ol><div className="tv-order-page__items"><h2>Items</h2>{order.items.map((item, index) => <div key={`${item.name}-${index}`}><span>{item.quantity}× {item.name}{item.addOns.length ? ` · ${item.addOns.map((addon) => addon.name).join(', ')}` : ''}</span><strong>{money(item.lineTotal)}</strong></div>)}</div><dl className="tv-order-page__totals"><div><dt>Subtotal</dt><dd>{money(order.subtotal)}</dd></div>{order.deliveryFee > 0 && <div><dt>Delivery · {order.deliveryAreaName}</dt><dd>{money(order.deliveryFee)}</dd></div>}{order.discountAmount > 0 && <div><dt>Discount {order.discountCode ? `(${order.discountCode})` : ''}</dt><dd>-{money(order.discountAmount)}</dd></div>}<div><dt>Total</dt><dd>{money(order.total)}</dd></div></dl><div className="tv-order-page__facts"><p><strong>{order.orderType === 'delivery' ? 'Delivery' : 'Pickup'}</strong>{order.orderType === 'delivery' ? ` · ${order.deliveryAddress}` : ''}</p>{order.notes && <p>Notes: {order.notes}</p>}</div></section><a className="tv-order-page__link" href="/menu">Continue shopping</a></main>;
}
